import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Toaster} from 'react-hot-toast'
import Navbar from "@/components/navbar";
import QueryProvider from "@/providers/query-client";
import { StoreProvider } from "@/providers/store-providers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
    <html lang="en">
        <QueryProvider>
          <StoreProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Toaster />
      </body>
      </StoreProvider>
      </QueryProvider>
    </html>
    
  );
}
